### ISSUE TITLE
detect editing?

### ISSUE THREAD

**Issue by phelios** [emojirades/emojirades#85]
Just an idea, often when players go back and edit typo, do we want to detect that as a win?

**Comment by michael-robbins** [comment]
I'll investigate how edits are pushed through the API, as they might be a different class of messages and being ignored... or not....

**Comment by michael-robbins** [comment]
So as it turns out, edits are a message 'subtype', and I've wired in support for handling message edit events.

Buuut I've only done it for the purposes of seeing if a winner edits a message to include emojis and then progress the game state (winner posted).

I've specifically made it not then proceed to look at message edits in respect to 'user guesses'

Guess I could indeed remove the block and just make all user edits considered as new guesses too....
Would there be any weird issues here? Do we see this often where users don't spam new messages, but edit old ones?

**Comment by michael-robbins** [comment]
OK so just reviewing my logic on this, we detect edit events that are <30s from a message post and consider them valid guesses still, anything older is ignored.

So calling this issue closed, only took 4 years!
